package semestral;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author artur
 */
public class ReporteCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteCliente
     */
    public ReporteCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JRBG_reporte = new javax.swing.ButtonGroup();
        JRB_apellido = new javax.swing.JRadioButton();
        JRB_cedula = new javax.swing.JRadioButton();
        JRB_compra = new javax.swing.JRadioButton();
        btn_reporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Reporte de Cliente");

        JRBG_reporte.add(JRB_apellido);
        JRB_apellido.setText("Ordenado por apellido");

        JRBG_reporte.add(JRB_cedula);
        JRB_cedula.setText("Ordenado por cedula");

        JRBG_reporte.add(JRB_compra);
        JRB_compra.setText("Ordenado por compra anual");

        btn_reporte.setText("GENRAR REPORTE");
        btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteActionPerformed(evt);
            }
        });

        jLabel1.setText("Sleccione una opcion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JRB_cedula)
                    .addComponent(JRB_compra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(JRB_apellido)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(JRB_apellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRB_cedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRB_compra)
                .addGap(37, 37, 37)
                .addComponent(btn_reporte)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteActionPerformed
        try{
           String URL = "jdbc:mysql://localhost:3306/java";
            String user = "root";
            String pass = "";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(URL,user,pass);
            JasperReport reporteC =(JasperReport) JRLoader.loadObjectFromFile("C:\\Users\\215\\Documents\\NetBeansProjects\\Semestral\\src\\semestral\\RCliente.jasper");
             Map <String,Object> parametro = new HashMap <String,Object>();
            if(JRB_apellido.isSelected()){
                parametro.put("OrdenarPor","APELLIDO");
                JasperPrint j = JasperFillManager.fillReport(reporteC,parametro,con);
                JasperViewer jv = new JasperViewer(j,false);
                jv.setTitle("Reporte Cliente por Apellido");
                jv.setVisible(true);
            }else if(JRB_cedula.isSelected()){
                parametro.put("OrdenarPor","CEDULA");
                JasperPrint j = JasperFillManager.fillReport(reporteC,parametro,con);
                JasperViewer jv = new JasperViewer(j,false);
                jv.setTitle("Reporte Cliente por Cedula");
                jv.setVisible(true);
            }else if(JRB_compra.isSelected()){
                parametro.put("OrdenarPor","COMPRAANUAL");
                JasperPrint j = JasperFillManager.fillReport(reporteC,parametro,con);
                JasperViewer jv = new JasperViewer(j,false);
                jv.setTitle("Reporte Cliente por Compra Anual");
                jv.setVisible(true);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al mostrar reporte cliente: "+e);
        }  
    }//GEN-LAST:event_btn_reporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JRBG_reporte;
    private javax.swing.JRadioButton JRB_apellido;
    private javax.swing.JRadioButton JRB_cedula;
    private javax.swing.JRadioButton JRB_compra;
    private javax.swing.JButton btn_reporte;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
